# Generated by Django 2.1.7 on 2020-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('write_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
                ('category', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('write_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
                ('parent_category', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('write_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('reviewer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
