# Generated by Django 2.1.7 on 2020-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200507_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='/static/assets/img/image-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
