# Generated by Django 2.1.7 on 2020-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200609_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='/static/assets/img/image-placeholder.jpg', max_length=255, null=True, upload_to=''),
        ),
    ]
